language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28

env:
  - RUST=stable
  - RUST=beta
  - RUST=nightly

install:
  - bash .travis/install.sh

script:
  - source $HOME/.cargo/env
  - export PATH=$PATH:${HOME}/.ndk/arm/bin:${HOME}/.ndk/arm64/bin:${HOME}/.ndk/x86/bin:${HOME}/.ndk/x86_64/bin
  - set -e
  - ./gradlew assembleDebug
  - ./gradlew test

jobs:
  include:
    - stage: lint
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.2
          - android-28
      env:
        - RUST=nightly
      install:
        - bash .travis/install.sh
        - source $HOME/.cargo/env
        - rustup component add clippy-preview
        - rustup component add rustfmt-preview
      script:
        - source $HOME/.cargo/env
        - export PATH=$PATH:${HOME}/.ndk/arm/bin:${HOME}/.ndk/arm64/bin:${HOME}/.ndk/x86/bin:${HOME}/.ndk/x86_64/bin
        - cargo clippy -- --deny clippy::all
        - cargo fmt --all -- --check
        - bash .travis/lint.sh
        - ./gradlew ktlint
        - bash .travis/detekt.sh

    - stage: deploy
      branches:
        only:
          - master
      if: tag IS present AND fork = false
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.2
          - android-28
      env:
        - RUST=stable
      install:
        - bash .travis/install.sh
      script:
        - set -e
        - source $HOME/.cargo/env
        - export PATH=$PATH:${ANDROID_HOME}/build-tools/28.0.2
        - export PATH=$PATH:${HOME}/.ndk/arm/bin:${HOME}/.ndk/arm64/bin:${HOME}/.ndk/x86/bin:${HOME}/.ndk/x86_64/bin
        - gpg --decrypt --cipher-algo AES256 --passphrase $KEYSTORE_ENCRYPT_PASSWORD --batch .travis/keystore.jks.gpg > .travis/keystore.jks
        - bash .travis/release.sh
      deploy: &releases
        provider: releases
        api_key: $GITHUB_TOKEN
        file: "dist/vplan.apk"
        skip_cleanup: true
        on:
          tags: true
