-keep class de.fschillerg.vplan.vplan.Change { *; }
-keep class de.fschillerg.vplan.vplan.NativeVplan { *; }
-keep class de.fschillerg.vplan.vplan.Vplan { *; }
-keep class de.fschillerg.vplan.vplan.VplanClient { *; }
-keep class de.fschillerg.vplan.vplan.VplanDate { *; }
-keep class de.fschillerg.vplan.vplan.Weekday { *; }
-keep class de.fschillerg.vplan.vplan.WeekType { *; }
